name: Lint
on: [workflow_dispatch, pull_request]
env:
  TERM: xterm-256color
  CLANG_VERSION: 19

jobs:
  clang-format:
    name: Clang-Format
    runs-on: ubuntu-latest
    steps:
    - name: Install clang-format
      run: |
        major_version=$(lsb_release -rs | cut -d'.' -f1)
        if [ "$major_version" -lt "24" ]; then
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          CODENAME=$(lsb_release --short --codename)
          sudo add-apt-repository "deb https://apt.llvm.org/${CODENAME}/ llvm-toolchain-${CODENAME}-${CLANG_VERSION} main"
        fi
        sudo apt update
        sudo apt install -y clang-format-${CLANG_VERSION}

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run clang-format
      run: |
        if ! git clang-format-${CLANG_VERSION} --binary=clang-format-${CLANG_VERSION} --diff --commit=origin/master
        then
          echo -e "\033[1;31mCode style does not match clang-format"
          exit 1
        fi
