name: Build - macOS
on: [workflow_dispatch, push, pull_request]
env:
  TERM: xterm-256color

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Build - macOS Xcode
            runs-on: macos-latest
            compiler: clang
            cxx-compiler: clang++
            cmake-args: -G Xcode

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate project
      run: cmake -S . -B build ${{ matrix.cmake-args }} -D CMAKE_BUILD_TYPE=Release -D BUILD_SHARED_LIBS=OFF
      env:
        CC: ${{ matrix.compiler }}
        CXX: ${{ matrix.cxx-compiler }}

    - name: Build project
      run: cmake --build build --config Release

    - name: Run tests
      run: ctest --verbose -C Release
      working-directory: build

    - name: Dump proxy info
      run: scutil --proxy

    - name: Set proxy settings (networksetup)
      run: |
        networksetup -setautoproxyurl "Ethernet" http://wpad/wpad3.dat
        networksetup -setproxyautodiscovery "Ethernet" on
        networksetup -setwebproxy "Ethernet" my.proxy7.com 8007
        networksetup -setsecurewebproxy "Ethernet" my.proxy8.com 8008
        networksetup -setproxybypassdomains "Ethernet" hi.com world.com

    - name: Check proxy settings (networksetup)
      shell: bash
      run: |
        out=$(./proxycli config auto_discover)
        echo "Auto discovery: $out"
        if [ "$out" = "enabled" ]; then
          echo "Auto discovery set successfully"
        else
          echo "Auto discovery set failed"
          exit 1
        fi
        out=$(./proxycli config auto_config_url)
        echo "Auto config url: $out"
        if [ "$out" = "http://wpad/wpad3.dat" ]; then
          echo "Auto config url set successfully"
        else
          echo "Auto config url set failed"
          exit 1
        fi
        out=$(./proxycli config proxy http)
        echo "Proxy (http): $out"
        if [ "$out" = "my.proxy7.com:8007" ]; then
          echo "Proxy (http) set successfully"
        else
          echo "Proxy (http) set failed"
          exit 1
        fi
        out=$(./proxycli config proxy https)
        echo "Proxy (https): $out"
        if [ "$out" = "my.proxy8.com:8008" ]; then
          echo "Proxy (https) set successfully"
        else
          echo "Proxy (https) set failed"
          exit 1
        fi
        out=$(./proxycli config bypass_list)
        echo "Proxy bypass: $out"
        if [ "$out" = "hi.com,world.com" ]; then
          echo "Proxy bypass set successfully"
        else
          echo "Proxy bypass set failed"
          exit 1
        fi
      working-directory: build/test/Release
