name: Build - macOS
on: [workflow_dispatch, push, pull_request]
env:
  TERM: xterm-256color

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Build - macOS Xcode
            runs-on: macos-latest
            compiler: clang
            cxx-compiler: clang++
            cmake-args: -G Xcode

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate project
      run: cmake -S . -B build ${{ matrix.cmake-args }} -D CMAKE_BUILD_TYPE=Release -D BUILD_SHARED_LIBS=OFF
      env:
        CC: ${{ matrix.compiler }}
        CXX: ${{ matrix.cxx-compiler }}

    - name: Build project
      run: cmake --build build --config Release

    - name: Run tests
      run: ctest --verbose -C Release
      working-directory: build

    - name: Dump proxy info
      run: scutil --proxy
